# Site settings
title: SC Allemang
email: sca@scallemang.ca
description: > # this means to ignore newlines until "baseurl:"
  Hello, world! My Name is Sam Allemang. I do web design in Toronto and am helping Andray Domise build the Techsdale project and volunteer for CoderDojoTO. I'm available for web-related work through Cloud Surfing Media.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: scallemang
github_username:  scallemang

# Build settings
markdown: kramdown
permalink: pretty

# Tag/category page creation from ryancmorrissey.com
blog:
    tags:
        url: /blog/tags/
        title_prefix: "blog - tag: "
        layout: tag.html